//created Mar 01, 2023 - 22:32:47
package it.cnr.isti.labsedc.concern.event;
import it.cnr.isti.labsedc.concern.event.ConcernAbstractEvent;
import it.cnr.isti.labsedc.concern.event.ConcernProbeEvent;
import it.cnr.isti.labsedc.concern.event.ConcernBaseEvent;
import it.cnr.isti.labsedc.concern.utils.KieLauncher;
import it.cnr.isti.labsedc.concern.utils.Calculator;
import it.cnr.isti.labsedc.concern.notification.NotificationManager;

//Monitor the transaction amount

dialect "java"

declare ConcernBaseEvent
    @role( event )
    @timestamp( timestamp )
    @expires(1m)
end

rule "counting transaction in a timeframe"
no-loop
salience 10
dialect "java"
when 

Number( longValue > 100 ) from accumulate(
	        ConcernBaseEvent(name == "TransactionStart", senderID == "SevenBullsSimProbe" ) over window:time( 60s ),
	        count(1))   	 		
    then
	NotificationManager.NotifyViolation("SevenBullsSimProbe", "Warning - actually more than 100 transaction per minute has been fired - Rule fired:" + drools.getRule().getName(), drools.getRule().getName(), drools.getRule().getMetaData());
end