//created Feb 17, 2023 - 23:22:50
package it.cnr.isti.labsedc.concern.event;
import it.cnr.isti.labsedc.concern.event.ConcernAbstractEvent;
import it.cnr.isti.labsedc.concern.event.ConcernProbeEvent;
import it.cnr.isti.labsedc.concern.event.ConcernBaseEvent;
import it.cnr.isti.labsedc.concern.utils.KieLauncher;
import it.cnr.isti.labsedc.concern.utils.Calculator;
import it.cnr.isti.labsedc.concern.notification.NotificationManager;
import java.util.*;
import java.lang.*;

//Monitoring the optimization requests queue 

dialect "java"

declare ConcernBaseEvent
    @role( event )
    @timestamp( timestamp )
    @expires(1m)
end

rule "Monitoring the number of errors in DLQ Queue"
no-loop
salience 10
dialect "java"
when 

$aEvent: ConcernBaseEvent(
		this.getSenderID == "SevenBullsSimProbe",
		this.getDestinationID == "Monitoring",
		this.getName == "Errors_in_DLQ");
		
		eval(Calculator.checkIfItIsGreater($aEvent.getData(),1000));
		
    then
	NotificationManager.NotifyViolation("SevenBullsSimProbe", "Warning - The number of errors in DLQ Queue is overriding threshold - Rule fired:" + drools.getRule().getName(), drools.getRule().getName(), drools.getRule().getMetaData());
	retract($aEvent);	
end