//created on: Dec 1, 2021
package it.cnr.isti.labsedc.concern.event;
import it.cnr.isti.labsedc.concern.event.ConcernAbstractEvent;
import it.cnr.isti.labsedc.concern.event.ConcernBaseEvent;
import it.cnr.isti.labsedc.concern.event.ConcernProbeEvent;
import it.cnr.isti.labsedc.concern.utils.KieLauncher;

dialect "java"

declare ConcernBaseEvent
    @role( event )
    @timestamp( timestamp )
end
            
rule "moreThanOneConn"
	no-loop
	salience 10
	dialect "java"
when
	$aEvent : ConcernBaseEvent(
	this.getName == "Connect to:",
	this.getData == "LocalPlanner",
	this.getProperty == "port:1234");
	
	$bEvent : ConcernBaseEvent(
	this.getName == "Connect to:",
	this.getData == "LocalPlanner",
	this.getProperty == "port:1234",
	this after $aEvent);
then
	KieLauncher.printer("Double connection to " + $aEvent.getData() + " on " + $aEvent.getSpecificExtension());	
	retract($aEvent);
	retract($bEvent);	
end
