//created Jan 24, 2023 - 17:41:32
package it.cnr.isti.labsedc.concern.event;
import it.cnr.isti.labsedc.concern.event.ConcernAbstractEvent;
import it.cnr.isti.labsedc.concern.event.ConcernProbeEvent;
import it.cnr.isti.labsedc.concern.event.ConcernBaseUnencryptedEvent;
import it.cnr.isti.labsedc.concern.utils.KieLauncher;
import it.cnr.isti.labsedc.concern.utils.Encrypter;
import it.cnr.isti.labsedc.concern.notification.NotificationManager;


dialect "java"

declare ConcernBaseUnencryptedEvent
    @role( event )
    @timestamp( timestamp )
    @expires( 2m )
end

rule "NON-CRYPTO_BASELINE"
no-loop
salience 1000
dialect "java"
when
    $aEvent : ConcernBaseUnencryptedEvent(
        this.senderID == "UNENCRYPTED_Probe",
        this.destinationID == "Monitoring",
        this.name == "UnencryptedMessage",
        this.encryption == "none",
        this.consumed == false);
        
then
    $aEvent.setConsumed(true);
    update($aEvent);
end
